remote_theme: vaibhavvikas/jekyll-theme-minimalistic
color-scheme: light

title: Which national team has/had to travel the most to their games?
description: Estimating 2026 World Cup group-stage travel distances between team training sites and match venues.

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

navigation:
  - name: Read me
    link: ./index.html
  - name: Dashboard
    link: ./dashboard
  - name: Methodology
    link: ./methodology
  - name: Python Script
    link: ./process
