remote_theme: vaibhavvikas/jekyll-theme-minimalistic
color-scheme: light

title: Which national team has to fly the most to/from their games?
description: Estimating round-trip air travel distances for 2026 World Cup group-stage matches between team training camps and match venues.

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

navigation:
  - name: Read me
    link: ./index.html
  - name: Executive Summary
    link: ./executive-summary
  - name: Dashboard
    link: ./dashboard
  - name: Python Script
    link: ./process
